import type { ProductDefinition } from './types';

export const PRODUCTS: ProductDefinition[] = [
  {
    id: 'solshade-lotion',
    name: 'Solshade Lotion',
    category: 'Personal Care',
    description: 'Fast-moving sun guard with strong warm-weather demand.',
    basePrice: 18,
    baseSupply: 58,
    baseDemand: 1.08,
    storagePerUnit: 1,
    volatility: 0.12,
    priceElasticity: 0.08,
    peakMonth: 7,
  },
  {
    id: 'draftpod-fan',
    name: 'Draftpod Fan',
    category: 'Home Comfort',
    description: 'Pocket desk fan that spikes whenever rooms start feeling close.',
    basePrice: 34,
    baseSupply: 42,
    baseDemand: 0.98,
    storagePerUnit: 1,
    volatility: 0.14,
    priceElasticity: 0.1,
    peakMonth: 7,
  },
  {
    id: 'brightnest-tabs',
    name: 'Brightnest Tabs',
    category: 'Cleaning',
    description: 'Dissolving cleaning tablets with spring reset momentum.',
    basePrice: 14,
    baseSupply: 64,
    baseDemand: 1.02,
    storagePerUnit: 1,
    volatility: 0.09,
    priceElasticity: 0.07,
    peakMonth: 4,
  },
  {
    id: 'quickpatch-roll',
    name: 'Quickpatch Roll',
    category: 'Home Repair',
    description: 'Instant repair wrap that moves faster before rough weather.',
    basePrice: 22,
    baseSupply: 38,
    baseDemand: 0.96,
    storagePerUnit: 1,
    volatility: 0.13,
    priceElasticity: 0.09,
    peakMonth: 10,
  },
  {
    id: 'hearthleaf-sachets',
    name: 'Hearthleaf Sachets',
    category: 'Pantry',
    description: 'Steep-and-go drink sachets that perk up in cold snaps.',
    basePrice: 12,
    baseSupply: 72,
    baseDemand: 0.9,
    storagePerUnit: 1,
    volatility: 0.08,
    priceElasticity: 0.06,
    peakMonth: 12,
  },
  {
    id: 'pawprint-bites',
    name: 'Pawprint Bites',
    category: 'Pet Care',
    description: 'Low-volatility pet snacks that keep cash moving between spikes.',
    basePrice: 16,
    baseSupply: 76,
    baseDemand: 1.05,
    storagePerUnit: 1,
    volatility: 0.07,
    priceElasticity: 0.05,
    peakMonth: 5,
  },
];
